name: google_maps_webservice
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 0.0.20-nullsafety.2
homepage: https://github.com/lejard-h/google_maps_webservice

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  meta: ^1.3.0
  json_annotation: ^3.0.1

dev_dependencies:
  test: ^1.16.0
  pedantic: ^1.10.0
  build_runner: 1.10.3
  json_serializable: ^3.5.1
  # coverage: ^1.0.0
